main.tf
dynamodb is not supported in govcloud so this module will always fail to run.  Setting count to false allows this to run correctly.
=> disable dynamodb data source when not needed

main.tf
The aws_vpc_dhcp_options resource [supports tags](https://www.terraform.io/docs/providers/aws/r/vpc_dhcp_options.html#tags) so we should add them to be consistent.
=> Add tags to the DHCP Options resource

outputs.tf
Outputs directly referencing resource IDs that are only conditionally
created are not valid. Use the concat * trick to make sure we always
have a valid value for these outputs.
=> make sure outputs are always valid

README.md, main.tf, variables.tf
This PR adds enables passing in external EIPs to be assigned to the NAT Gateways (Fixes #37).
To that end, this PR:
* Adds two variables: a boolean flag to enable disable the feature and a list of EIP IDs to be used if the feature is enabled.
* Adds the logic to either create new NAT Gateway IPs or use the EIP IDs passed in to the module
* Adds a restriction to the required terraform version (>= 0.10.13) since the selection of either created or passed in IPs requires local values.
I have not documented the feature because I would like some input from the maintainers of the module on where to document this. If the PR is accepted, I could add the documentation to the main README file, to the existing examples, or even make a new example.
=> Allow passing in EIPs for the NAT Gateways

README.md, examples/complete-vpc/main.tf, examples/issue-44-asymmetric-private-subnets/README.md, examples/issue-44-asymmetric-private-subnets/main.tf, examples/issue-44-asymmetric-private-subnets/outputs.tf, examples/issue-46-no-private-subnets/README.md, examples/issue-46-no-private-subnets/main.tf, examples/issue-46-no-private-subnets/outputs.tf, main.tf
=> Added fix for issue when no private subnets are defined

README.md, main.tf
There was a previous commit ( https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/38 ) to enforce version **0.10.13** to be able to use the **Local Values** feature.
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0103-august-30-2017
The right version was **0.10.3** and not **0.10.13** which doesn't exist.This is causing us issues now when we are running terraform:
> The currently running version of Terraform doesn't meet the
> version requirements explicitly specified by the configuration.
> Please use the required version or update the configuration.
> Note that version requirements are usually set for a reason, so
> we recommend verifying with whoever set the version requirements
> prior to making any manual changes.
> 
>   Module: module.vpc
>   Required …
=> Downgraded require_version from 0.10.13 to 0.10.3

main.tf
This PR makes the routing tables for the private subnets ignore changes to their `propagating_vgws`.
When configuring VPN Gateways it is normal to define `aws_vpn_gateway_route_propagation` resources to automatically configure route propagation between the VPN Gateway and a routing table. However, without this PR, terraform will continuously propose changes to the infrastructure, adding route propagation in one run and removing it the next.
First run:
```
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ aws_vpn_gateway_route_propagation.private_subnets_vpn_routing[0]
id:             <computed>
route_table_id: "rtb-aaa"
vpn_gateway_id: "vgw-xxx"
+ aws_vpn_gateway_route_propagation.private_subnets_vpn_routing[1]
id: …
```
=> Ignore changes to propagating_vgws of private routing table

main.tf
If the name field doesn't contain lower-case only, it throws an error.
=> Lowercase database subnet group name

main.tf
Following conversation on #56 I believe the one Elastic IPs was the only resource that wasn't tagged.
=> Issue #56: Added tags for elastic ips

outputs.tf
=> Issue #58: Add ElastiCache subnet group name output.

README.md
Hello,
First of all, thanks for your work! That module is very useful.
I tried to use External NAT Gateway IPs by following the readme instructions without success until I read the [documentation](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.9.1?tab=inputs). From my understanding, the variable `external_nat_ip_ids` is not read if the variable `reuse_nat_ips` is not set to `true`. 
I suggest to add a small note about that combination directly into the readme. :wink:
=> Improve documentation about the usage of external NAT gateway IPs

main.tf
I noticed the module is currently creating one association per public subnet for the s3 endpoint, but there's only one public route table so it's only necessary to create one association.
=> Only create one public route association for s3 endpoint

main.tf, variables.tf
So that the default route table will be named and tagged accordingly instead of being unnamed and untagged.
=> Manage Default Route Table under Terraform

variables.tf
Fixes #86
@egarbi - What do you think about this?
=> Added default CIDR block as 0.0.0.0/0

README.md, examples/issue-108-route-already-exists/README.md, examples/issue-108-route-already-exists/main.tf, examples/issue-108-route-already-exists/outputs.tf, main.tf
Multiple issues are related:
- #108
- #102
- #95
To-do:
=> Fix for RouteAlreadyExist error

main.tf
=> Creates a single private route table when single_nat_gateway is true

README.md, main.tf, variables.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/117 by adding a new variable called `one_nat_gateway_per_az`. This enables the feature that only one NAT gateway is created for each availability zone. By default, the number of NAT Gateways created is equal to `max_subnet_length`, which is calculated as follows
```hcl
max_subnet_length = "${max(length(var.private_subnets), length(var.elasticache_subnets), length(var.database_subnets), length(var.redshift_subnets))}"
```
For example, if a user specified three database subnet CIDR blocks, four ElastiCache subnet CIDR blocks, and five private subnet CIDR blocks, then five NAT Gateways would be created since five is the maximum of those lists.
As per https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/117, …
=> Fix #117 - Add `one_nat_gateway_per_az` functionality

README.md, examples/complete-vpc/README.md, examples/complete-vpc/main.tf, main.tf, outputs.tf, variables.tf
For situations where Lambda functions are used (e.g., with API Gateway) inside the VPC, the Lambdas need to be configured with subnet IDs from which they can allocate ENIs.  The PR simply adds subnets across the AZs for that.
=> Adding "infra subnets" as a class

README.md, examples/simple-vpc/main.tf, variables.tf
just a typo in the docs and in the
public_subnet_tags in the simple example
=> Fixing typo overriden -> overridden

README.md, examples/simple-vpc/README.md, examples/simple-vpc/main.tf, examples/simple-vpc/outputs.tf, main.tf, outputs.tf, variables.tf
Set `assign_generated_ipv6_cidr_block = true` to enable it on VPC.
=> Add minimum support for IPv6 to VPC

README.md, examples/secondary-cidr-blocks/README.md, examples/secondary-cidr-blocks/main.tf, examples/secondary-cidr-blocks/outputs.tf, main.tf, outputs.tf, variables.tf
Based entirely on #161 
Kudos to @JohnnyC08 and @matthiasr
Big thanks for implementing a solution using `local.vpc_id` as a hint to Terraform.
=> Add secondary CIDR block support

main.tf
Re-orders the tag merging to be consistent with Terraform's map merging strategy, and provides the user greater control over specific resource tagging when tags are inherited from upstream.
**Short version**
The merging strategy of merging maps for a given object should always follow the pattern:
```hcl
tags = "${merge(map(default_map, least_specific_map, ..., ..., most_specific_map)}"
```
This is also documented on the [Terraform Interpolation](https://www.terraform.io/docs/configuration/interpolation.html) page:
> Returns the union of 2 or more maps. The maps are consumed in the order provided, and duplicate keys overwrite previous entries.
This PR changes the tag merging strategy to honor that.
**Long version**
I use CloudPosse's …
=> Re-ordering tag merging

variables.tf
https://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpn-gateway.html
=> change to Amazon default ASN (as per API)

README.md, main.tf, variables.tf
Closes #149
Unfortunately, in Terraform 0.11 it is not possible to disable argument conditionally by specifying `null`.
This PR will have to wait until Terraform 0.12 is released.
=> Added amazon_side_asn to vpn_gateway

main.tf, variables.tf
Similarly to `create_database_internet_gateway_route`, this adds the `create_database_nat_gateway_route` parameter to create routes in database subnets to the unique/per-AZ/per-subnet NAT Gateways.
=> adding option to create a route to nat gateway in database subnets

README.md, examples/complete-vpc/main.tf, examples/test_fixture/README.md, main.tf, outputs.tf, variables.tf
Extend endpoints so that AWS Systems Manager could be setup utilizing endpoints only.
=> Extend endpoints for AWS Systems Manager use

main.tf, variables.tf
Not sure if it is better to keep this out of the module but useful for current project I'm working on.
=> Added option to create ECR api and dkr endpoints

README.md, main.tf, outputs.tf, variables.tf
I updated the VPC module by adding a public subnet for Redshift because in our use case we needed to access it from Kinesis. 
Because VPC endpoint for [Kinesis is not yet supported by Redshift](https://docs.aws.amazon.com/redshift/latest/mgmt/enhanced-vpc-working-with-endpoints.html) , we had to add Redshift to a public subnet and made it publicly accessible.
=> Redshift public subnets

README.md, examples/network-acls/README.md, examples/network-acls/main.tf, examples/network-acls/outputs.tf, main.tf, outputs.tf, variables.tf
This PR is heavily based on #174 by @kinghuang 
Added functionalities:
Known limitations:
- IPv6 is not supported in NACL rules
=> Network ACLs

README.md, examples/simple-vpc/main.tf, outputs.tf
=> Added missing VPC endpoints outputs

README.md, examples/complete-vpc/main.tf, main.tf, outputs.tf, variables.tf
also add missing list and map types in certain variables
=> add support for KMS VPC endpoint creation

README.md, outputs.tf
Facilitates resource access manager, subnet sharing across accounts
=> Add Output Of Subnet ARNs

README.md, variables.tf
Clarifying that `enable_dhcp_options` is required when specifying `dhcp_options_*` variables.
=> Improving DHCP options docs

README.md, main.tf, outputs.tf, variables.tf
add the following endpoints:
* ecs
* ecs agent
* ecs telemetry
=> ECS endpoint

README.md, main.tf, outputs.tf, variables.tf
Based on 
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/269#issuecomment-496150401 request to back port changes
=> Add Missing VPC Endpoints Backport - terraform 0.11.X

README.md, main.tf, variables.tf
This PR adds Kinesis Streams and Firehose VPC endpoints
=> kinesis streams and firehose VPC endpoints

README.md, examples/ipv6/README.md, examples/ipv6/main.tf, examples/ipv6/outputs.tf, examples/ipv6/variables.tf, examples/network-acls/main.tf, examples/secondary-cidr-blocks/main.tf, examples/simple-vpc/main.tf, main.tf, outputs.tf, variables.tf
Heavily based on #300 by @StephenKing
=> Add IPv6 support

.pre-commit-config.yaml, CHANGELOG.md, README.md, examples/complete-vpc/main.tf, main.tf, variables.tf
* Added new variable for tags that are specific to VPC Endpoints.
* Added tags to each VPC Endpoint that consists of the the general tag map and VPC Endpoint specific tag map
=> Add tags to VPC Endpoints

.pre-commit-config.yaml, examples/network-acls/main.tf, main.tf
Updating VPC module to allow ICMP Network ACL rules.  Since from_port and to_port are ignored for ICMP rules, allowing user to leave these fields off makes sense.  We could make this more complicated and require from_port and to_port if protocol is not ICMP but that would make the module less readable.
=> Allow ICMP Network ACL rules

README.md, examples/complete-vpc/main.tf, main.tf, variables.tf
=> Added support for EC2 ClassicLink

main.tf
Add support for `ipv6_cidr_block` in `*_{in|out}bound_acl_rules`.  As a
conseqeunce, the (ipv4) `cidr_block` is made optional.
The other options have been reindented but are otherwise unchanged.
After this patch, you can use ipv6-ACLs like this:
```
module "vpc" {
source = "terraform-aws-modules/vpc/aws"
name = "Test"
cidr = "10.1.0.0/16"
enable_ipv6 = true
public_subnet_assign_ipv6_address_on_creation = true
azs              = ["us-east-1a","us-east-1b"]
public_subnets   = ["10.1.1.0/24","10.1.2.0/24"]
private_subnets  = ["10.1.3.0/24","10.1.4.0/24"]
public_subnet_ipv6_prefixes = [ 1, 2 ]
enable_nat_gateway = true
public_dedicated_network_acl = true
public_inbound_acl_rules =  [
{ rule_number = 600, rule_action = "allow", from_port =    80, to_port =    80, protocol = "tcp", cidr_block …
```
=> support `ipv6_cidr_block` in network acls

main.tf
fixes the following current issue:
```
Error: Error in function call
on .terraform_stage/modules/main_vpc/terraform-aws-modules-terraform-aws-vpc-5358041/main.tf line 917, in resource "aws_route" "private_ipv6_egress":
917:   route_table_id              = element(aws_route_table.private.*.id, count.index)
|----------------
| aws_route_table.private is empty tuple
| count.index is 0
Call to function "element" failed: cannot use element function with an empty
list.
```
=> fix ipv6 enable

.circleci/config.yml, .pre-commit-config.yaml, README.md, versions.tf
The `for_each` loop was released with Terraform `0.12.6` and, due to its usage in `main.tf`, is required for this module to work. This commit sets that minimum version and updates `.circleci/config` accordingly.
As a result this also fixes the currently failing CircleCI tests.
=> Set minimum terraform version to 0.12.6 (fixes circleci)

.pre-commit-config.yaml, README.md, main.tf, variables.tf
add support for specifying AZ in VPN Gateway.
unfortunately i cannot test this.
=> Add support for specifying AZ in VPN Gateway

README.md, flow-logs.tf, versions.tf, vpc-flow-logs.tf
Add tags to Flow Logs
based on the change added in terraform-providers/terraform-provider-aws#12273
=> Flow Logs Tagging Support

README.md, main.tf, variables.tf
Adds support for Intra Subnet VPN Route Table propagation
Closes #352
No.
Copy-Pasted From same config for Public & Private Subnets
=> feat: Add intra subnet VPN route propagation

variables.tf
I ran into the same issue as https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/126 because there's nothing in the documentation making it clear that `create_database_subnet_group` only has an effect if you also specify `database_subnets`.
=> docs: Document create_database_subnet_group requiring database_subnets

README.md, outputs.tf, variables.tf, vpc-endpoints.tf
This pr adds VPC endpoint for Simple Email Service (SES).
SES endpoint was recently added to AWS and I want to use it in terraform.
No
I've created VPC with ses endpoint and sent an email.
=> feat: Add VPC Endpoint for SES

README.md, outputs.tf
this will just add owner_id output to module
I use owner_id/Account ID in different policies and building dynamic variables, for example
codebuild
```
buildspec = templatefile("files/buildspec.yml", {
aws_region   = var.region,
ecr_registry = "${module.vpc.owner_id}.dkr.ecr.${var.region}.amazonaws.com/${module.label.id}-ecr"
})
```
or iam policy
```
"Resource": [
"arn:aws:ecr:${var.region}:${module.vpc.owner_id}:repository/ecr-${var.plat}/influxdb",
```
none
tested calling from other resources and modules as in example above
=> feat: add vpc_owner_id to outputs

versions.tf
- Set minimum version required which will allow for 0.13 to start being used with module
Closes #453
=> feat: Enable support for Terraform 0.13 as a valid version by setting minimum version required

main.tf, versions.tf
Add support for tagging egress only internet gateway
Allows tagging egress only internet gateway. tagging you resources is cool.
No
Created VPC from IPV6 example to see if egress only internet gateway tags are created
Closes #433
=> feat: Add support for tagging egress only internet gateway

README.md, main.tf, variables.tf
Add support for disabling of creating an IGW for public subnets for a case that is specified in #446
Closes #446
No
Ran simple example with the `disable_igw_creation` set to `true`
=> feat: add support for disabling IGW for public subnets

README.md, variables.tf
=> docs: Fix typo in nat_public_ips

.circleci/config.yml
Circleci tests are failing the last releases. It is complaining about the regexall function that is not included in the current 0.12.6 version.
I saw that the regexall function was not recognized because of an older terraform version that is used in circlci tests. I bumped the terraform version in order to fix the test.
None as far as I know.
I ran the oneliners from the circleci config file.
=> fix: bumping terraform version from 0.12.6 to 0.12.7 in circleci to include regexall function

README.md, versions.tf
Bumping aws-provider requirement to ">= 2.57"
Should fix https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/478
There is newer provider version available.
As stated [here](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.0.0)
Ran it locally
=> feat: bump version of aws provider version to support 3.*

vpc-endpoints.tf
Fixes InvalidServiceName for elasticbeanstalk_health (Issue #481)
None
We used this branch to create the endpoint successfully in eu-central-1
=> fix: InvalidServiceName for elasticbeanstalk_health

README.md, examples/network-acls/README.md, examples/network-acls/outputs.tf, outputs.tf, versions.tf
Add ARN outputs for igw, cgw, vgw, default vpc, acls
Allows creating IAM policies to restrict certain actions for resources created by the module.
No
Simple VPC example ran.
=> feat: add arn outputs for: igw, cgw, vgw, default vpc, acls

README.md, variables.tf, vpc-endpoints.tf
Added ability to create RDS endpoint to VPC 
The creation of RDS endpoint does not exist
N/A
N/A
N/A
I have tested it by creating vpc, and verify the endpoint is setup correct
=> feat: Add ability to create RDS endpoint to VPC

README.md, examples/complete-vpc/main.tf, variables.tf, vpc-endpoints.tf
Added ability to create CodeDeploy endpoint to VPC
AWS recently added support for [CodeDeploy VPC endpoints
](https://aws.amazon.com/ru/about-aws/whats-new/2020/08/aws-codedeploy-now-supports-deployments-to-virtual-private-cloud-endpoints/)
This change doesn't break backwards compatibility with current release
I've tested it by running `complete-vpc` example and check if endpoints setup correctly.
=> feat: Add ability to create CodeDeploy endpoint to VPC

README.md, variables.tf, vpc-endpoints.tf
Allows not setting s3 vpc endpoint for public subnet
Closes #427
No, default value keeps original functionality
=> feat: add `enable_public_s3_endpoint` variable for S3 VPC Endpoint for public subnets

README.md, outputs.tf, variables.tf, vpc-endpoints.tf
Add the new Textract vpc endpoint - https://docs.aws.amazon.com/textract/latest/dg/vpc-interface-endpoints.html
=> feat: Add Textract vpc endpoint

examples/simple-vpc/main.tf, main.tf
Reverts terraform-aws-modules/terraform-aws-vpc#492
The fix was not necessary and not working as expected.
=> revert: Create only required number of NAT gateways

examples/network-acls/main.tf, main.tf
This fix sets the value for the `subnet_ids` attribute of the `aws_default_network_acl` to be any subnets created by the module that are not allocated to any other `aws_network_acl` resources.
#529 
This fix involves the usage of the `setsubtract`, `compact`, and `flatten` functions which should not break any backward compatibility.
I did the following:
- Added the `manage_default_network_acl` attribute set as `true` to the `network-acls` example
- `terraform apply`
- Set the `private_dedicated_network_acl` attribute as `false` in the example
- `terraform apply`
- `terraform plan`
- Noticed that the plan was complaining that the previously created subnets would be removed from the `aws_default_network_acl` resource
- `terraform apply`
- `terraform plan`
- Noticed that the plan was *still* …
=> fix: Resource aws_default_network_acl orphaned subnet_ids

README.md, examples/complete-vpc/README.md, examples/complete-vpc/main.tf, examples/complete-vpc/outputs.tf, outputs.tf, variables.tf, vpc-endpoints.tf
AWS recently announced [PrivateLink support for Lambda](https://aws.amazon.com/blogs/aws/new-use-aws-privatelink-to-access-aws-lambda-over-private-aws-network/). This PR serves to add the functionality to this module. 
So the new endpoint can be used by projects already integrated with this module.
None.
Locally.
=> feat: Lambda VPC Endpoint

README.md, variables.tf, vpc-flow-logs.tf
Adding `vpc_flow_log_permissions_boundary` so that developers who are required to specify a permissions boundary on IAM roles can enable the VPC Flow Log feature in this module
In many AWS setups, developers are required to assume a role in order to make changes to AWS resources. One of the recommended security measures that is recommended by AWS is to allow roles the ability to create other roles only if a permissions boundary is set directly on the role. This prevents developers (in an assumed-role session) from [unintentionally/intentionally] creating a role with, for example, super powers/administrative rights. Without the ability to set a permissions boundary on the VPC Flow Logs IAM role, those who are bound by this permissions boundary restraint will not be able to enable the VPC …
=> feat: Adding vpc_flow_log_permissions_boundary

README.md, outputs.tf
Fixes #551 
Changes the descriptions of 
default_vpc_id
default_vpc_arn
default_vpc_cidr_block
default_vpc_default_network_acl_id
default_vpc_route_tabnle_id
default_vpc_security_group_id
default_vpc_enable_dns_hostnames
default_vpc_enable_dns_support
default_vpc_instance_tenancy
default_vpc_main_route_table_id
in both README.md and outputs.tf to avoid confusion.
=> docs: Clarifies default_vpc attributes

README.md, outputs.tf
RDS endpoint is missing from the outputs.
RDS endpoint is missing from the outputs.
=> fix: Adding missing RDS endpoint to output.tf

README.md, examples/complete-vpc/README.md, examples/complete-vpc/versions.tf, examples/ipv6/README.md, examples/ipv6/versions.tf, examples/issue-108-route-already-exists/README.md, examples/issue-108-route-already-exists/versions.tf, examples/issue-44-asymmetric-private-subnets/README.md, examples/issue-44-asymmetric-private-subnets/versions.tf, examples/issue-46-no-private-subnets/README.md, examples/issue-46-no-private-subnets/versions.tf, examples/manage-default-vpc/README.md, examples/manage-default-vpc/versions.tf, examples/network-acls/README.md, examples/network-acls/versions.tf, examples/secondary-cidr-blocks/README.md, examples/secondary-cidr-blocks/versions.tf, examples/simple-vpc/README.md, examples/simple-vpc/main.tf, examples/simple-vpc/versions.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/versions.tf, versions.tf
Related to #573 since VPC endpoint service_type became available in AWS provider version 3.10.
=> feat: Upgraded minimum required versions of AWS provider to 3.10

.gitignore, .pre-commit-config.yaml, README.md, examples/complete-vpc/README.md, examples/ipv6/README.md, examples/issue-108-route-already-exists/README.md, examples/issue-44-asymmetric-private-subnets/README.md, examples/issue-46-no-private-subnets/README.md, examples/manage-default-vpc/README.md, examples/network-acls/README.md, examples/secondary-cidr-blocks/README.md, examples/simple-vpc/README.md, examples/vpc-flow-logs/README.md, examples/vpc-separate-private-route-tables/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
=> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

README.md
…hat modules support the 'count' argument (as of Terraform 0.13).
Updated the 'Conditional Creation' section of the documentation to reflect the fact that Terraform 0.13+ supports the count argument in module blocks (https://www.terraform.io/docs/language/meta-arguments/count.html).
The documentation was outdated and didn't fully apply to newer versions of Terraform.
No breaking changes.
I read it, and my IDE has a spellchecker?
=> docs: update the 'conditional creation' section of the README for TF 0.13+

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/versions.tf
- align ci-cd static checks to use individual minimum Terraform versions
- ensure that the modules are all following a similar workflow and the static checks that performed
- No
- ci-cd static checks
=> chore: align ci-cd static checks to use individual minimum Terraform versions

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete-vpc/README.md, examples/ipv6/README.md, examples/issue-108-route-already-exists/README.md, examples/issue-44-asymmetric-private-subnets/README.md, examples/issue-46-no-private-subnets/README.md, examples/manage-default-vpc/README.md, examples/network-acls/README.md, examples/secondary-cidr-blocks/README.md, examples/simple-vpc/README.md, examples/vpc-flow-logs/README.md, examples/vpc-separate-private-route-tables/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
=> chore: update documentation and pin `terraform_docs` version to avoid future changes

modules/vpc-endpoints/README.md
Private DNS is not a valid setting for the S3 interface endpoint.
Updating documentation.
The documentation for this module is invalid.
None
Have tried to run the code as provided in the documentation and it will not work.
=> chore: Private DNS cannot be used with S3 endpoint

vpc-flow-logs.tf
Many Cloudrail users are running into this:
```
Rule: Ensure IAM policies pass Access Analyzer policy validation without WARNING and SUGGESTION issues
- 1 Resources Exposed:
-----------------------------------------------
- Exposed Resource: [module.vpc.aws_iam_role.vpc_flow_log_cloudwatch[0]] (../../vpc-flow-logs.tf:44)
Violating Resource: [module.vpc.aws_iam_role.vpc_flow_log_cloudwatch[0]]  (../../vpc-flow-logs.tf:44)
Evidence:
Line 5, Col 13:
| Add a value to the empty string in the Sid element
| See https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-policy-checks.html#access-analyzer-reference-policy-checks-suggestion-empty-sid-value
```
Simply because there's no SID in the assume policy and it violates AWS best practices.
To avoid a Cloudrail violation for …
=> fix: Fixed SID for assume role policy for flow logs

examples/vpc-separate-private-route-tables/README.md, examples/vpc-separate-private-route-tables/outputs.tf
Fix copy/paste mistake of the outputs in VPC with separate private route tables example
This still working but maybe misleading 
I don't think any of these are breaking changes, just fix copy/paste mistake. No existing properties are being changed.
=> fix: Fixed mistake in separate private route tables example

README.md, outputs.tf
Added ID of DHCP options to outputs
We need it to put in IAM policy which allow to maintain objects which created by this module.
It has backwards compatibility to all previous versions of module which has DHCP options object.
=> docs: Added ID of aws_vpc_dhcp_options to outputs

README.md, examples/complete-vpc/README.md, examples/complete-vpc/versions.tf, examples/ipv6/README.md, examples/ipv6/versions.tf, examples/issues/README.md, examples/issues/versions.tf, examples/manage-default-vpc/README.md, examples/manage-default-vpc/versions.tf, examples/network-acls/README.md, examples/network-acls/versions.tf, examples/outpost/README.md, examples/outpost/versions.tf, examples/secondary-cidr-blocks/README.md, examples/secondary-cidr-blocks/versions.tf, examples/simple-vpc/README.md, examples/simple-vpc/versions.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/versions.tf, examples/vpc-separate-private-route-tables/README.md, examples/vpc-separate-private-route-tables/versions.tf, modules/vpc-endpoints/README.md, modules/vpc-endpoints/versions.tf, versions.tf
Fixes #679 
Updates the minimum terraform version to 0.12.31 to support the new HashiCorp Signatures
Terraform versions before 0.12.31 only support the AWS Provider version up to 3.37.0 because the GPG key used to create the signatures was changed at this point.
None. This change only increments the terraform version to the latest minor version of the same release version.
- Verified that for each of the examples fails init when the module's aws provider version is set to 3.38 and the terraform version is 0.12.26
- Verified that it inits as expected when the terraform version is set to 0.12.31.
=> fix: Update the terraform to support new provider signatures

README.md, examples/complete-vpc/README.md, examples/complete-vpc/main.tf, examples/complete-vpc/versions.tf, examples/ipv6/README.md, examples/ipv6/versions.tf, examples/issues/README.md, examples/issues/versions.tf, examples/manage-default-vpc/README.md, examples/manage-default-vpc/versions.tf, examples/network-acls/README.md, examples/network-acls/versions.tf, examples/outpost/README.md, examples/outpost/versions.tf, examples/secondary-cidr-blocks/README.md, examples/secondary-cidr-blocks/versions.tf, examples/simple-vpc/README.md, examples/simple-vpc/versions.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/versions.tf, examples/vpc-separate-private-route-tables/README.md, examples/vpc-separate-private-route-tables/versions.tf, main.tf, modules/vpc-endpoints/README.md, modules/vpc-endpoints/versions.tf, versions.tf
Minimal change adding the `device_name` property into the `aws_customer_gateway` resource.
I already had a Customer Gateway created, and when I imported the resource state into this module, terraform was trying to recreate the resource. Without this change, I  cannot use the module with pre-existent AWS customer gateway resources with the "device_name" set. 
There are no break changes. 
I have two Gateway resources. One with the `device_name` property set, and the other don't set. 
```
customer_gateways = {
"cgw1"      = {
bgp_asn     = 65000
ip_address  = "1.2.3.4"
device_name = "USG"
},
"cgw2" = {
bgp_asn    = 65000
ip_address = "5.6.7.8"
},
}
```
I tested both importing the resources and created the resources from scratch.
=> feat: Added device_name to customer gateway object.

examples/complete-vpc/README.md, examples/complete-vpc/main.tf, modules/vpc-endpoints/main.tf, outputs.tf
- correct `for_each` map on VPC endpoints to propagate endpoint maps correctly by using the map comprehension. this also solves for the case where `create = false` and avoiding the `Error: Inconsistent conditional result types. The true result value has the wrong type: element types must all match for conversion to map.` error
- updated `complete-vpc` example to demonstrate/validate use case with security group issue shown in #650
- update outputs to use new `try()` and recommended index `[0]`/`[*]` syntax
- Closes #650
- No
- Validated with `complete-vpc` example; no plan diff from current `master`
=> fix: Correct `for_each` map on VPC endpoints to propagate endpoint maps correctly

examples/complete-vpc/main.tf
fix for dynamodb resource not found error in the example.
=> chore: Fixed code in examples (dynamodb resource not found error)

examples/complete-vpc/README.md, examples/complete-vpc/main.tf, main.tf
As noted in the [terraform docs][0], subnets using the default network acl
will generate a persistent diff if they are not specified to the aws_default_network_acl
resource. This module was handling subnets created by the module, but
of course is not aware of subnets created externally to the module.
The docs suggest using lifecycle ignore_changes as an option to avoid
the persistent diff, which is the approach implemented in this patch.
Fixes #736
[0]: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_network_acl#managing-subnets-in-a-default-network-acl
None
1. cd examples/network-acls
2. run terraform apply
3. manually create a new subnet in the vpc
4. run terraform apply
5. view that no changes are planned
=> fix: Addresses persistent diff with manage_default_network_acl

examples/complete-vpc/main.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/main.tf, examples/vpc-flow-logs/versions.tf, modules/vpc-endpoints/main.tf
This change is to allow for create to work within each vpc endpoint object. If the create is outside of a vpc endpoint then that will take priorty over the specific vpc endpoints create.
This will make the script alot more flexible and fine grain. As you can go down to object level to specify which objects should be created or not. Making a lot more use cases possible.
The only thing that was introduced that would be debtable is try but it seems try has been there for a long time so seem like it is backwards compatible. 
Yes I have an example project which I tested this on. I tested with multiple use cases to make sure.
This change will also default create to true with object level vpc endpoints just like it has been. Meaning create is still optional for object level and resource level …
=> feat: Change to allow create variable within specific vpc objects

modules/vpc-endpoints/main.tf
Prevent creation of data resources for VPC endpoints that are disabled.
The data resources and resources for VPC endpoints are now in sync.
No breaking change
=> fix: Declare data resource only for requested VPC endpoints

.pre-commit-config.yaml, outputs.tf
- Compact CIDR block outputs to avoid empty diffs
- Closes #743 
- No
=> fix: Compact CIDR block outputs to avoid empty diffs

modules/vpc-endpoints/main.tf
Allow the `security_group_ids` argument to `aws_vpc_endpoint` to take `null` values when the endpoint is of Interface type
When defining a VPC endpoint of type Interface, if no `security_group_ids` are defined either as defaults or in the individual endpoint definition, the value passed to the `aws_vpc_endpoint` resource is an empty list.
This PR modifies that behaviour so that if no `security_group_ids` are defined, the `aws_vpc_endpoint` receives a `null` value instead of an empty list. Semantically, it makes no difference and it causes the default security group to be associated with the endpoint. However, functionally, a `null` value enables the use of `aws_vpc_endpoint_security_group_association` resources without triggering changes on the `aws_vpc_endpoint` resource.
I have tested …
=> fix: Allow `security_group_ids` to take `null` values

examples/manage-default-vpc/README.md
This PR corrects a broken link in the `Manage Default VPC` [README](examples/manage-default-vpc/README.md).
Fixes a broken link to the relevant AWS provider doc.
None.
=> docs: Fix broken link in default VPC example readme

vpc-flow-logs.tf
We can use `try` function to check if resources used in `local` return the value and if not set it to the `null` (#841).
It is related to the [Second run of destroy failed when VPC Flow log is enabled and full module output is set](841).
No breaking changes
=> fix: Prevent an error when VPC Flow log log_group and role is not created

README.md, examples/simple-vpc/main.tf, main.tf, variables.tf
Add public and private tags per az
I want to set up kubernetes controllers that can use a specific subnet by tag. I could use name but our names have a lot of information in them. I would much rather be able to tag a subnet by AZ with certain tags like the AZ itself or the cluster I'm trying to target for this AZ.
None
```sh
cd examples/simple-vpc
terraform init
terraform plan
```
```hcl
+ resource "aws_subnet" "public" {
+ tags                                           = {
+ "Example"           = "ex-simple-vpc"
+ "GithubOrg"         = "terraform-aws-modules"
+ "GithubRepo"        = "terraform-aws-vpc"
+ "Name"              = "overridden-name-public"
+ "availability-zone" = "eu-west-1a"
}
+ tags_all                                       = {
+ "Example"           = "ex-simple-vpc"
+ …
```
=> feat: Add public and private tags per az

examples/complete-vpc/main.tf
Enable TLS inbound for Session Manager
I use Session Manager quite extensively as it avoids the need for managing SSH Key pairs. The complete example had all of the endpoints but was missing the security group definitions for a couple, so I added them here.
Enable testers to spin up EC2 instances without the need for SSH Key Pairs
None
I've validated that this works in 2 separate AWS accounts.
=> chore: Updated example to enable TLS Inbound for Session Manager

examples/simple/main.tf, main.tf
- Add missing private subnets to max subnet length local
- Allows creating private only subnets
Error from current implementation:
- No
=> fix: Add missing private subnets to max subnet length local

README.md, examples/ipv6-dualstack/main.tf, main.tf
Based on the nat64/dns64 [docs](https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-nat64-dns64.html), a route is required to utilize dns64 & nat64 for IPv6 only services to non-IPv6 services. 
- Add private subnet route for dns64.
- Add database subnet route for dns64.
- Enable nat gateway in dualstack example to test.
Fixes #923 
I tested this both in our internal stack and against the [ipv6-dualstack](examples/ipv6-dualstack/main.tf) example.  New route should be created as long as nat gateways are enabled other criteria you'll see in the PR. 
I only updated private subnet route tables and database subnet route tables since it seemed to fit the existing patterns but if I missed anything or you feel differently, I'm open to any suggestions.  Thanks!
=> fix: Add dns64 routes

examples/complete/README.md
Maybe the folder name or link address isn't right, I really don't know. Either way this is the right link address.
It helps people find the files needed to run the example.
=> docs: Correct link address for `simple` example

.pre-commit-config.yaml, examples/complete/README.md, examples/complete/main.tf, examples/complete/outputs.tf, modules/vpc-endpoints/README.md, modules/vpc-endpoints/main.tf, modules/vpc-endpoints/outputs.tf, modules/vpc-endpoints/variables.tf
- Add support for creating a security group for VPC endpoint(s)
- VPC endpoints require a security group, and most of the interface endpoint services use https/443 - this change lets users makes these requirements easier for users when utilizing the VPC endpoint sub-module while also allowing them to extend its use
- No
=> feat: Add support for creating a security group for VPC endpoint(s)

main.tf
"The module does not take into account the number of intra_subnets, since the latter are designed to have no Internet access via NAT Gateway."
the concept is right, the number of intra subnets should not determine the number of nat gateways. However it currently does. Today I tried to create a vpc with :
3 intra subnets, 
2 public subnets, 
2 private subnets. 
As a result, I had 3 nat gateways (because i choose configuration nat gateway per subnet) so i had:
nat-gateway-a located in public network A
nat-gateway-b located in public network B
nat-gateway-c located in public network A (second nat gateway in the same subnet).
makes the module work in accordance with the assumptions, documentation and logic. Keeping an unnecessary nat gateway with a public ip is just an extra cost, and 2 nat …
=> fix: The number of intra subnets should not influence the number of NAT gateways provisioned

modules/vpc-endpoints/main.tf
- Correct VPC endpoint private DNS resolver `for_each` key
- Resolves #1028
=> fix: Correct VPC endpoint private DNS resolver `for_each` key

main.tf
In case of customer_gateway is used with TGW this changes will allow us to replace ip_address in the single `terraform apply`
```
│ Error: deleting EC2 Customer Gateway (cgw-xxxxxxxxx): IncorrectState: The customer gateway is in use.
│       status code: 400, request id: xxxxxx-994b-xxxx-xxx-xxxxxx
```
No
Was tested on production system
=> fix: Added create_before_destroy to aws_customer_gateway

.github/workflows/lock.yml, .github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/stale-actions.yaml, .pre-commit-config.yaml, examples/separate-route-tables/README.md
- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No
=> fix: Update CI workflow versions to remove deprecated runtime warnings

modules/vpc-endpoints/main.tf
Adds feature to allow overriding for each `aws_vpc_endpoint` `service_name` property, but defaulting to data if not defined.
Additionally this allows users to use specify fips endpoints if needed.
fixes #1054 
N/A
Have a PR here for an example where this was tested using changes in my `.terraform` directory which I replicated in this fork.
https://github.com/defenseunicorns/terraform-aws-vpc/pull/113
=> feat: Allow setting vpc endpoints as an input for each endpoint

main.tf
Fixes issue with routes creation for IPv6 private subnets when you have following setup:
```
private_subnets = [
"10.0.0.0/24", "10.0.1.0/24", "10.0.2.0/24",
"10.0.3.0/24", "10.0.4.0/24", "10.0.5.0/24",
]
private_subnet_ipv6_prefixes = [
1, 2, 3,
4, 5, 6
]
enable_nat_gateway     = true
single_nat_gateway     = false
one_nat_gateway_per_az = true
create_egress_only_igw = true
```
thanks to @RunCor399
- Resolves #1058
none
Before the change:
```
+ resource "aws_route" "private_ipv6_egress" {
+ destination_ipv6_cidr_block = "::/0"
+ egress_only_gateway_id      = (known after apply)
+ id                          = (known after apply)
+ instance_id                 = (known after apply)
+ instance_owner_id           = (known after apply)
+ network_interface_id        = (known after apply)
+ …
```
=> fix: Create the same number of IPv6 egress only gateway routes as the number of NAT gateways that are enabled/created

main.tf
Private IPv6 Egress routes are now only created when having at least a private subnet
Version 5.7.1 of the module solved the issue #1058 by limiting the amount of IPv6 egress routes created to the amount of NAT gateways provisioned (hence to the amount of Route Tables created).
However the condition that regulates the number of IPv6 egress routes created doesn't check if the creation of any private subnet is actually wanted 
- Resolves #1061
=> fix: Create private_ipv6_egress routes only when having at least one private subnet

modules/vpc-endpoints/README.md
Changed relative links to absolute links, otherwise they don't work when displayed on registry.terraform.io
It fixes broken links on the terraform registry
No
Not
=> docs: Updated links to examples in README

README.md, examples/complete/main.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/main.tf, variables.tf, vpc-flow-logs.tf
Allow custom IAM Role and Policy names for the VPC flow log either by specifying the entire name, or by providing a prefix.
Some organizations require specific prefixes or naming schemes on IAM policies and roles. This allows support for that following the same pattern as in other `terraform-aws-modules`
Not a breaking change.
=> feat: Allow custom VPC Flow Log IAM Role name and IAM Policy name

main.tf
Makes the count on `aws_route` dynamic instead of fixed at 1
Fixes #1087 
Not that I'm aware of.
=> feat: Add route to `0.0.0.0/0` & `::/0` (when IPv6 is enabled) on all public route tables

README.md, vpc-flow-logs.tf
This pull request updates the AWS VPC terraform module to use log group ARNs instead of wildcard ("*") as the resource in the flow log policy. This change restricts the flow log policy to specific log groups, improving security and ensuring that only authorized log groups can receive flow log data.
The previous implementation allowed logging to any log group in AWS CloudWatch Logs, which could potentially lead to unauthorized access to log data. The updated implementation ensures that flow log data is only sent to designated log groups specified by their ARNs.
This change does not break backwards compatibility with the current major version.
Thank you.
=> feat: Restrict flow log policy to use log group ARNs

README.md, vpc-flow-logs.tf
… ensuring compatibility with AWS GovCloud and other partitions
Update flow log ARNs to use partition from aws_partition data source, ensuring compatibility with AWS GovCloud and other partitions. This was due to the least privilege change in 5.12.0, 5.11.0 and earlier are fine. See PR [#1088](https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/1088)
Currently when deploying to GovCloud with flow logs you get the following error
```
MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:logs:us-gov-west-1:0123456789:log-group:/aws/vpc-flow-log/vpc-012345:*"
```
No
=> fix: Update flow log ARNs to use partition from aws_partition data source

.pre-commit-config.yaml, modules/vpc-endpoints/main.tf
PR delivers feature for VPC endpoints - if name is not defined, then default name is constructed from service name.
#1150 
There are no breaking changes.
=> feat: Define default name for VPC endpoint

modules/vpc-endpoints/README.md, modules/vpc-endpoints/main.tf, modules/vpc-endpoints/versions.tf
Adds cross-region capabilities for VPC endpoints.
AWS added cross-region support for VPC Private link in November 2024. Support for that feature was added in the AWS [Terraform provider release 5.83](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.83.0). 
No breaking changes, backwards compatible.
Tested and validated both the old syntax (of not providing the `service_region` as part of `var.endpoints` as well as with adding it.
=> feat: Support for cross region VPC endpoints

modules/vpc-endpoints/main.tf
Currently, if we pass ` service_region=null` (rather than not passing it at all), the module fails as it passes on `[null]` rather than `null` to the underlying data source.
See description and [the comment in this PR that added cross-region support](https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/1161#issuecomment-2616115424) in the first place.
Non breaking, makes things more robust and covers all all cases (no `service_region` passed, `service_region=null` passed, valid service region passed)
Tested passing no `service_region`, `service_region=null`, or a valid service region passed
=> fix: Fixed service_region argument in the VPC endpoint module

.pre-commit-config.yaml, examples/block-public-access/README.md, examples/block-public-access/main.tf, main.tf
Allows name tagging on aws_vpc_block_public_access_exclusion resource
Closes #1169 
To be able to set the name tag on the AWS resource
https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/1169
No breaking changes
=> feat: Allow setting custom tags on `aws_vpc_block_public_access_exclusion` resource

README.md, examples/block-public-access/README.md, examples/block-public-access/versions.tf, examples/complete/README.md, examples/complete/versions.tf, examples/ipam/README.md, examples/ipam/versions.tf, examples/ipv6-dualstack/README.md, examples/ipv6-dualstack/versions.tf, examples/ipv6-only/README.md, examples/ipv6-only/versions.tf, examples/issues/README.md, examples/issues/versions.tf, examples/manage-default-vpc/README.md, examples/manage-default-vpc/versions.tf, examples/network-acls/README.md, examples/network-acls/versions.tf, examples/outpost/README.md, examples/outpost/versions.tf, examples/secondary-cidr-blocks/README.md, examples/secondary-cidr-blocks/versions.tf, examples/separate-route-tables/README.md, examples/separate-route-tables/versions.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/versions.tf, modules/vpc-endpoints/README.md, modules/vpc-endpoints/versions.tf, versions.tf
Finally, I think upgrading the version to 6.0 everywhere in the module is good. :)
=> fix: Bump AWS provider requirement to v6 everywhere

modules/vpc-endpoints/README.md
Add missed parameter for VPC Endpoint Gateway service type in README
Without this parameter, VPC Endpoint with type "Interface" will be created.
No breaking changes.
N/A
=> docs: Update README.md for VPC Endpoints submodule
