terraform-aws-modules/terraform-aws-vpc

variables.tf
No functional changes. Just improvements to the variable description language.
=> Improve variable descriptions

main.tf, variables.tf
Adding the ability to add custom tags for the DHCP option set
=> Adding additional tags for DHCP option set

main.tf
Proposing change to routing table creation for private subnets to only create if private subnets are defined.
=> change conditional for private routes

examples/complete-vpc/main.tf, main.tf
=> Fixing edge case when VPC is not symmetrical with few private subnets

outputs.tf
=> Removed classiclink from outputs because it is not present in recent regions

main.tf
=> Make terraform recognize lists when using variables

main.tf
=>  Ensures the correct number of S3 and DDB VPC Endpoint associations

main.tf
=>  Added longer timeouts for aws_route create

main.tf, variables.tf
=> Added intra subnet suffix.

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, CHANGELOG.md, Makefile
Believe me, guys, I am also excited about this addition... :)
=> Added CHANGELOG.md

outputs.tf
I need in my policy generator the arn of vpc so I would like to include this
=> Added ARN of VPC in module output

.circleci/config.yml
Not sure if this is enough to fix CI.
=> Upgrade Docker Image to fix CI

CHANGELOG.md, README.md, main.tf, variables.tf
Adding additional VPC end points:
- Config
- Secrets Manager
- Codebuild
- Codecommit
- Git Codecommit
- Transfer Server
=> Additional VPC Endpoints

.circleci/config.yml, outputs.tf
- Added vpc_name as an output
- Modified circleci checks:
- Install missing curl binary for tflint checks
- Add default aws region required by aws module
- Modified init and validate steps to traverse directories
- Removed invalid (in 0.12.x) -check-variables flag
=> Add vpc name

README.md, main.tf, variables.tf
Same as #292 just for terraform 0.11.x.
=> Add tags to VPC Endpoints - terraform 0.11.x

.pre-commit-config.yaml, README.md, outputs.tf, variables.tf, vpc-endpoints.tf
CloudFormation, CodePipeline, Storage Gateway, AppMesh, Transfer, Service Catalog & SageMaker(Runtime & API)
=> Additionl Endpoints

.circleci/config.yml
Update TFLint to v0.12.1
Please explain the changes you made here and link to any relevant issues.
=> Update TFLint to v0.12.1

outputs.tf
Fix wrong ACM PCA endpoint id output
No.
=> fix: wrong ACM PCA output

main.tf
reorder tags to allow overriding Name tag
Closes #406
No
=> fix: Reorder tags to allow overriding Name tag in route tables

main.tf
Follow up to #525 
Related to https://github.com/hashicorp/terraform/pull/26387
=> fix: Removed ignore_changes to work with Terraform 0.14

.circleci/config.yml, README.md, examples/complete-vpc/README.md, examples/complete-vpc/versions.tf, examples/ipv6/README.md, examples/ipv6/versions.tf, examples/issue-108-route-already-exists/README.md, examples/issue-108-route-already-exists/versions.tf, examples/issue-44-asymmetric-private-subnets/README.md, examples/issue-44-asymmetric-private-subnets/versions.tf, examples/issue-46-no-private-subnets/README.md, examples/issue-46-no-private-subnets/versions.tf, examples/manage-default-vpc/README.md, examples/manage-default-vpc/versions.tf, examples/network-acls/README.md, examples/network-acls/versions.tf, examples/secondary-cidr-blocks/README.md, examples/secondary-cidr-blocks/versions.tf, examples/simple-vpc/README.md, examples/simple-vpc/versions.tf, examples/vpc-flow-logs/README.md, examples/vpc-flow-logs/versions.tf, examples/vpc-separate-private-route-tables/README.md, examples/vpc-separate-private-route-tables/versions.tf, versions.tf
=> fix: Updated min required version of Terraform to 0.12.21

README.md, outputs.tf, variables.tf, vpc-endpoints.tf
Added Codeartifact API/Repo vpc endpoints
Added this two endpoints to enable it
Adding new endpoints
I tested from my forked branch on my infra and works like a charm.
=> feat: Added Codeartifact API/Repo vpc endpoints

README.md, outputs.tf, variables.tf, vpc-endpoints.tf
Adding missing DMS endpoint
DMS endpoint is missing
=> feat: Adding VPC endpoint for DMS

vpc-endpoints.tf
=> fix: Fixed wrong count in DMS endpoint

examples/simple-vpc/outputs.tf
Just corrected a small typo in AZs
=> chore: Updated outputs in example

.github/workflows/pr-title.yml, .github/workflows/release.yml, .github/workflows/stale-actions.yaml, .pre-commit-config.yaml, .releaserc.json, examples/manage-default-vpc/main.tf, examples/manage-default-vpc/outputs.tf, examples/secondary-cidr-blocks/outputs.tf, examples/simple-vpc/outputs.tf, examples/vpc-flow-logs/outputs.tf, examples/vpc-separate-private-route-tables/outputs.tf
- Update `.releaserc.json` to ensure conventional-commit standards are used by semantic-releaser
- Update `.pre-commit-config.yaml` versions to latest and ensure `end-of-file-fixer` hook is used
- Add `pr-title.yml` GitHub workflow for ensuring PR titles follow conventional-commit standards
- Fix `release.yml` GitHub workflow to ensure release process does not run on forks; ref https://github.com/terraform-aws-modules/meta/issues/25
- Add `stale-actions.yaml` to ensure issues and pull requests are routinely cleaned up; copie from EKS repository
- Ensure organization configurations are aligned and standardized; most of these changes are copied from the current EKS repository
- No
- CI checks only
=> chore: Update release configuration files to correctly use conventional-commits

outputs.tf
=> fix: Fixed redshift_route_table_ids outputs

README.md
This PR fixes a typo in the REAME file.
Found a typo and think of fixing it.
No
=> chore: Typo on README - "One NAT Gateway per subnet" section

UPGRADE-3.0.md
Seems like the directory layout was modified, but this doc was not
=> chore: Proper link to complete vpc example

vpc-flow-logs.tf
=> fix: Fixed deprecation attribute warning with AWS provider v6
